# Generated by Django 3.2.5 on 2021-07-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
    ]
