name: "Build and deploy Github pages"

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: "Set up Python"
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: "Install Python dependencies"
        run: |
          cd docs
          pip install -r requirements.txt

      - name: "Build Sphinx Doc"
        run: |
          cd docs
          make html

      - name: "Deploy Github Pages"
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/build/html/
